language: python
sudo: false
dist: trusty
cache:
- apt
- pip
services:
- redis
python:
- '2.7'
- '3.5'
- '3.6'
env:
  global:
  - DISPLAY=:99.0
  matrix:
  - DJANGO=18
  - DJANGO=110
  - DJANGO=111
  - DJANGO=master
  - TOXENV=qa
matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO=master
  exclude:
  - env: DJANGO=master
    python: '2.7'
  - env: TOXENV=qa
    python: '2.7'
  - env: TOXENV=qa
    python: '3.5'
install:
- pip install --upgrade pip tox
- pip install -U coveralls
- sh -e /etc/init.d/xvfb start
before_script:
- |
  if [[ -z $TOXENV ]]; then
    export TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/\.//g')-dj$DJANGO
  fi
- echo $TOXENV
script:
- tox -e $TOXENV
after_success:
- coveralls
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: OzNShO+N3zL3LIyJ7Fu/TFgJTaI+FlZxLItjPTu5tAfvrxPWmKXJkA7b8znx5O2w0kSynk0R1Ddyd6Ri4AIyS5SGm2ZbvrTyIpaXPvWMBl1o8X/nH14f61HP2piEtnk24FBLTbublgC9N1G4w/166jAwv2dxS9aWJGioAlSOgH8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: codingjoe/django-s3file
