language: python
sudo: false
dist: trusty
cache:
- apt
- pip
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
python:
- '3.6'
env:
  global:
  - CHROME_DRIVER_VERSION=2.36
  matrix:
  - DJANGO=111
  - DJANGO=20
  - DJANGO=master
  - TOXENV=qa
matrix:
  fast_finish: true
  allow_failures:
  - env: DJANGO=master
install:
- pip install -qU pip tox codecov
before_script:
- mkdir bin
- curl -O https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d bin
- PATH=$PATH:$PWD/bin
- |
  if [[ -z $TOXENV ]]; then
    export TOXENV=py$(echo $TRAVIS_PYTHON_VERSION | sed -e 's/\.//g')-dj$DJANGO
  fi
- echo $TOXENV
script:
- tox -e $TOXENV
after_success:
- codecov
deploy:
  provider: pypi
  user: codingjoe
  password:
    secure: OzNShO+N3zL3LIyJ7Fu/TFgJTaI+FlZxLItjPTu5tAfvrxPWmKXJkA7b8znx5O2w0kSynk0R1Ddyd6Ri4AIyS5SGm2ZbvrTyIpaXPvWMBl1o8X/nH14f61HP2piEtnk24FBLTbublgC9N1G4w/166jAwv2dxS9aWJGioAlSOgH8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: codingjoe/django-s3file
