name: StandardJS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
    - name: Install Standard
      run: npm install -g standard
    - name: Run standard
      run: standard
